version: '3.7'
services:
  app:
    build: .
    image: myapp:0.8
    container_name: app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment: 
      RAILS_ENV: development
    depends_on:
      - mysql
      - webpack
    # :の左がhost（album_with_ficker）、右がコンテナ内、なのでwebapp以下を指定する必要があるので注意
    volumes:
      - ./webapp/:/usr/local/src
    command: "bash -c 'bundle && bin/rails db:migrate && bundle exec rails server'"
  webpack:
    build: .
    image: webpack:0.1
    container_name: webpack
    tty: true
    stdin_open: true
    ports:
      - "3500:3500"
    environment: {}
    depends_on:
      - mysql
    # :の左がhost（album_with_ficker）、右がコンテナ内、なのでwebapp以下を指定する必要があるので注意
    volumes:
      - ./webapp/:/usr/local/src
    command: "npm run webpack-dev-server"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    # ローカルでmysqlを立ち上げてportが被っているとエラーとなるので複数のappを触る作業中は注意
    ports:
      - 3306:3306 
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
volumes:
  mysql-data:
    name: mysql
